export const UPDATE_BURGER = "UPDATE_BURGER";
export const UPDATE_BASE_PRICE = "UPDATE_BASE_PRICE";

export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";

export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
